version: "v1"
project: "rethinkdb"
services:
  backend:
    db:
      image: "rethinkdb"
      cmd: "rethinkdb --bind all"
      domain: $URI
      port: 8080
      instances: 1
      mem: 512
      volumes:
        - path: "/data"
          size: "8GB"
