version: "v1"
project: "owncloud"
services:
  frontend:
    apache:
      image: "owncloud:10.0.3"
      instances: 1
      mem: 512
      domain: "$URI"
      port: 80
      volumes:
        - container_path: "/var/www/html"
          size: "8GB"
