version: "v1"
project: "owncloud"
services:
  frontend:
    apache:
      image: "owncloud"
      instances: 1
      mem: 512
      domain: "$URI"
      port: 80
      volumes:
        - container_path: "/var/lib/mysql"
          size: "8GB"
      dependencies:
        - "../../backend/mysql"
  backend:
    mysql:
      image: "mysql"
      instances: 1
      mem: 512
      env:
        - MYSQL_ROOT_PASSWORD: "$ROOTPW"
        - MYSQL_USER: "$MYSQLUSER"
        - MYSQL_PASSWORD: "$MYSQLPASSWORD"
        - MYSQL_DATABASE: "owncloud"
      volumes:
        - path: "/var/lib/mysql"
          size: "8GB"
