version: "v1"
project: "lychee"
services:
  frontend:
    apache:
      image: "mikemichel/lychee:3.1.3"
      instances: 1
      mem: 512
      domain: $URI
      port: 80
      volumes:
        - path: "/uploads"
          size: "8GB"
      dependencies:
        - "../../backend/mysql"
  backend:
    mysql:
      image: "mysql"
      instances: 1
      mem: 512
      volumes:
        - path: "/var/lib/mysql"
          size: "8GB"
      env:
        - MYSQL_ROOT_PASSWORD: "$DBROOT"
        - MYSQL_USER: "$DBUSER"
        - MYSQL_PASSWORD: "$DBPASS"
        - MYSQL_DATABASE: "lychee"
