version: "v1"
project: "wekan"
services:
  frontend:
    meteor:
      image: "wekanteam/wekan:v0.56"
      instances: 1
      mem: 512
      domain: $URI
      port: 80
      env:
        - MONGO_URL: "mongodb://mongodb.backend.wekan/wekan"
        - ROOT_URL: "https://$URI"
      dependencies:
        - "../backend/mongodb"
  backend:
    mongodb:
      image: "mongo:3.2.17"
      instances: 1
      mem: 512
      volumes:
        - path: "/data/db"
        - path: "/data/configdb"
      cmd: "mongod --smallfiles --oplogSize 128"
