version: "v1"
project: "wekan"
services:
  frontend:
    meteor:
      image: "mquandalle/wekan"
      instances: 1
      mem: 512
      domain: $URI
      port: 80
      env:
        - MONGO_URL: "mongodb://mongodb.backend.wekan/wekan"
        - ROOT_URL: "http://$URI"
      dependencies:
        - "../../backend/mongodb"
  backend:
    mongodb:
      image: "mongo"
      instances: 1
      mem: 512
      volumes:
        - path: "/data/db"
          size: "8GB"
      cmd: "mongod --smallfiles --oplogSize 128"
